### ISSUE TITLE
SEVERE: WORKBENCH:  java.io.IOException: Didn't get expected results.

### ISSUE THREAD

**Issue by mike-bioinfo** [forestbiotech-lab/sRNA-workflow#6]
Hi Bruno,

I am trying to run miRPursuit using reads with lengths between 20 - 30nt (plant small-RNA's) but I get this error:

java.io.IOException: Didn't get expected results.
	at uk.ac.uea.cmp.srnaworkbench.binaryexecutor.BinaryManager$7.run(BinaryManager.java:245)
	at uk.ac.uea.cmp.srnaworkbench.binaryexecutor.BinaryExecutor.execRandFold(BinaryExecutor.java:134)
	at uk.ac.uea.cmp.srnaworkbench.tools.mircat.Window.refold(Window.java:1242)
	at uk.ac.uea.cmp.srnaworkbench.tools.mircat.Window.updateOutputModules(Window.java:443)
	at uk.ac.uea.cmp.srnaworkbench.tools.mircat.Window.processWindows(Window.java:260)
	at uk.ac.uea.cmp.srnaworkbench.tools.mircat.Window.run(Window.java:121)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

May 16, 2019 5:32:13 PM uk.ac.uea.cmp.srnaworkbench.utils.LOGGERS.WorkbenchLogger log
SEVERE: WORKBENCH: 
java.lang.ArrayIndexOutOfBoundsException: 1
	at uk.ac.uea.cmp.srnaworkbench.tools.mircat.Window.updateOutputModules(Window.java:445)
	at uk.ac.uea.cmp.srnaworkbench.tools.mircat.Window.processWindows(Window.java:260)
	at uk.ac.uea.cmp.srnaworkbench.tools.mircat.Window.run(Window.java:121)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

May 16, 2019 5:32:13 PM uk.ac.uea.cmp.srnaworkbench.utils.LOGGERS.WorkbenchLogger log
SEVERE: WORKBENCH: uk.ac.uea.cmp.srnaworkbench.tools.mircat.Window.updateOutputModules(Window.java:445)
uk.ac.uea.cmp.srnaworkbench.tools.mircat.Window.processWindows(Window.java:260)
uk.ac.uea.cmp.srnaworkbench.tools.mircat.Window.run(Window.java:121)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

I have successfully ran it with the same dataset but trimmed at lengths between 20 - 37nt. I was looking at the log files but it would be great if you can tell me which one do you need me to post to solve this problem or just ignore this error.

**Comment by BrunoEVCosta** [comment]
I'll get back to you tomorrow.

**Comment by BrunoEVCosta** [comment]
Sorry, this has taken me some time to get back to this.

Please check the following.
In [project]/data/*noncons* check that there are sequences in the lib files identified as non conserved.

Check the log for running miRCat and try an individual run. The command should be in the log file for miRCat [project]/log/[run time]*mircat* or something like that. 

Does miRCat output any result?
I've seen this before but can't remember the cause.

**Comment by BrunoEVCosta** [comment]
The log file for that run, and the one specific for miRCat, will be the first piece of insight that can reveil some insight into this problem.

**Comment by BrunoEVCosta** [comment]
Please check the folders of the previous step if those input files have data

**Comment by BrunoEVCosta** [comment]
Please run the miRCat independently to access error origin. Command that was ran should be in logs. The issue technically isn't due to miRPursuit. If the issue is one of the inputs please re open this issue so it can be dealt with.
